objects/Movie__c.object
<CustomObject>
    <fields>
        <fullName>Year__c</fullName>
        <description>The year the movie was released to public</description>
        <inlineHelpText>Select 1st January of the Year the movie was released to public</inlineHelpText>
        <label>Year</label>
        <type>Date</type>
    </fields>
    <label>Movie</label>
    <nameField>
        <label>Movie Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Movies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/MovieOperationsTest.cls
@isTest
public class MovieOperationsTest {
    @isTest static void testMovieHasDefaultYear() {       
        // Perform test
        Test.startTest();
        Movie__c mov = new Movie__c(Name='Test Movie');
        Database.SaveResult result = Database.insert(mov);
        Test.stopTest();
        // Verify
        Movie__c testmov = [SELECT Year__c FROM Movie__c WHERE Id = :result.getId()];
        System.assertEquals(System.today(), testmov.Year__c);
    }
}